### ISSUE TITLE
feature request: child selection

### ISSUE THREAD

**Issue by atoms19** [JokeFat/Synxia#6]
Styling each individual child element can sometimes be quite cumbersome due to the repetition involved. To streamline this process, I propose a new selector mechanism that allows for selecting child elements based on a provided selector. This mechanism would require a new syntax, which, although potentially confusing at first, would greatly enhance efficiency.

Here’s an example scenario to illustrate the current issue. Consider a span tag containing several anchor tags. As you can see, there’s a significant amount of repetition:

```html
<span class="
    padding_1rem
    phone@display_none
">
    <a class="
        transition_0.3s
        color_--orange-9
        font-size_--font-size-3
        padding_1rem
        cursor_pointer
    ">Home</a>
    <a class="
        transition_0.3s
        color_--orange-9
        font-size_--font-size-3
        padding_1rem
        cursor_pointer
    ">Updates</a>
    <a class="
        transition_0.3s
        color_--orange-9
        font-size_--font-size-3
        padding_1rem
        cursor_pointer
    ">Contact</a>
</span>
```

### Suggested Syntax

To reduce this redundancy, I propose the following syntax:

```html
<span class="
    padding_1rem
    phone@display_none

    a)transition_0.3s
    a)color_--orange-9
    a)font-size_--font-size-3
    a)padding_1rem
    a)cursor_pointer
    a)hover:background_--blue-2
">
    <a>Home</a>
    <a>Updates</a>
    <a>Contact</a>
</span>
```

The `child query)` syntax, such as `a)`, would allow for applying styles to all matching child elements, saving a considerable amount of time and effort. This approach would not only reduce repetition but also improve code maintainability.

Additionally, the syntax could be extended to other selectors, such as `#id)background_red` or `.list-item)padding_0`. While cursor replication in editors like VS Code can mitigate the typing effort, this new selector mechanism would further simplify and enhance the styling process.

I am eagerly awaiting the introduction of groups and hope this suggestion is taken into consideration for future enhancements.

Kind regards.

**Comment by JokeFat** [comment]
<span class="
    padding_1rem
    transition_0.3s
    color_--orange-9
    hover:color_--red-2
    font-size_--font-size-3
    padding_1rem
    cursor_pointer
    ">
    <a class="
        
    ">Home</a>
    <a class="
    
    ">Updates</a>
    <a class="
        
    ">Contact</a>
</span>   

just make a parent element that gives those classes to its children

what about specific child selection
just add a class to that specific child

also
if you didn't want to style a specific parent
you could've just made a child to that parent
that would've been a parent to the <a>s
and styled it instead
